### ISSUE TITLE
Missing data isn't detected

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/test_registry#1]
The travis job for this repo has two stages. The second stage, which runs the download section of the datagetter, doesn't seem to run: https://travis-ci.org/ThreeSixtyGiving/test_registry/jobs/277385974/config

**Comment by Bjwebb** [comment]
The step does run, it just has a separate Travis page: https://travis-ci.org/ThreeSixtyGiving/test_registry/jobs/277385975 - you can see both of these listed on https://travis-ci.org/ThreeSixtyGiving/test_registry/builds/277385973. I think this display was buggy earlier, but seems to be fixed now.

Not sure why it missed some data going offline though.

**Comment by Bjwebb** [comment]
I think what's happened here is that we've managed to successfully download the 404 page, so we aren't getting flagged a download failure. We should probably detect the status code.

**Comment by Bjwebb** [comment]
We now check the status code.
